set(SUITE_SPARSE_ROOT /home/dso_port/dso/thirdparty/SuiteSparse)

FIND_PATH(CHOLMOD_INCLUDE_DIR NAMES cholmod.h amd.h camd.h
    PATHS
    ${SUITE_SPARSE_ROOT}/include
  )

FIND_LIBRARY(CHOLMOD_LIBRARY NAMES cholmod
     PATHS
     ${SUITE_SPARSE_ROOT}/lib
   )

FIND_LIBRARY(AMD_LIBRARY NAMES SHARED NAMES amd
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )

FIND_LIBRARY(CAMD_LIBRARY NAMES camd
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )

FIND_LIBRARY(SUITESPARSECONFIG_LIBRARY NAMES suitesparseconfig
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )




FIND_LIBRARY(COLAMD_LIBRARY NAMES colamd
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )

FIND_LIBRARY(CCOLAMD_LIBRARY NAMES ccolamd
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )

FIND_LIBRARY(METIS_LIBRARY NAMES metis
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )

SET(CHOLMOD_LIBRARIES ${CHOLMOD_LIBRARY} ${AMD_LIBRARY} ${CAMD_LIBRARY} ${COLAMD_LIBRARY} ${CCOLAMD_LIBRARY} ${METIS_LIBRARY})



IF(CHOLMOD_INCLUDE_DIR AND CHOLMOD_LIBRARIES)
  SET(CHOLMOD_FOUND TRUE)
ELSE(CHOLMOD_INCLUDE_DIR AND CHOLMOD_LIBRARIES)
  SET(CHOLMOD_FOUND FALSE)
ENDIF(CHOLMOD_INCLUDE_DIR AND CHOLMOD_LIBRARIES)

# Look for csparse; note the difference in the directory specifications!
FIND_PATH(CSPARSE_INCLUDE_DIR NAMES cs.h
  PATHS
  ${SUITE_SPARSE_ROOT}/include
  )


FIND_LIBRARY(CSPARSE_LIBRARY NAMES cxsparse
  PATHS
  ${SUITE_SPARSE_ROOT}/lib
  )

IF(CSPARSE_INCLUDE_DIR AND CSPARSE_LIBRARY)
  SET(CSPARSE_FOUND TRUE)
ELSE(CSPARSE_INCLUDE_DIR AND CSPARSE_LIBRARY)
  SET(CSPARSE_FOUND FALSE)
ENDIF(CSPARSE_INCLUDE_DIR AND CSPARSE_LIBRARY)

